name: CICD pipeline for ExpanseTrakerApp

on: push

jobs:
    git-clone:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v4
            - name: print done message
              run : echo 'Code is pushed!!!' 