name: CICD pipeline for ExpanseTrakerApp

on: 
  push:
    branches:
      features

jobs:
    git-clone:
        runs-on: ubuntu-latest
        steps:
              # step1 checkout for git repository
            - name: git clone checkout
              uses: actions/checkout@v4
              # step2 setup Docker
            - name: set up Docker buildx
              run : docker/setup-buildx-action@v3
              # step3 Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
             # Step4 Build Docker image
            - name: Build the Docker image
              run: |
                docker build -t ${{secrets.DOCKERHUB_USERNAME}}/expancetrackerapp:latest
             # setp5 Push image to DockerHub registery
            - name: Push image to Docker Hub reg
              run: |
                docker push ${{secrets.DOCKERHUB_USERNAME}}/expancetrackerapp:latest